- name: "Enable '{{ user_or_group_str }}' sudo auth: {{ enable_sudo_auth | default(true) }}"
  ansible.builtin.set_fact:
    enable_auth: "{{ enable_sudo_auth | default(true) }}"

- name: "Require sudo password for '{{ user_or_group_str }}' auth: {{ req_sudo_password }}"
  ansible.builtin.set_fact:
    nopassword_opt: "{{ '' if req_sudo_password else 'NOPASSWD: ' }}"
  when: req_sudo_password is defined

- name: "Limit '{{ user_or_group_str }}' auth to list of commands"
  ansible.builtin.set_fact:
    allowed_cmds: "{{ auth_cmd_list | join(',') }}"
  when: auth_cmd_list is defined

- name: "Set '{{ user_or_group_str }}' full/limited auth"
  ansible.builtin.include_tasks: func/edit_sudoers_opt/main.yml
  vars:
    description: "'{{ user_or_group_str }}' auth"
    config_lines: >-
      {{ user_or_group_str }} ALL=(ALL) {{ nopassword_opt | default('') }}{{ allowed_cmds | default('ALL') }}
    task_state: "{{ 'present' if enable_auth else 'absent' }}"

