- name: "Set time between sudo password asks"
  ansible.builtin.include_tasks: func/edit_sudoers_opt/main.yml
  vars:
    description: "set password wait-period before ask again"
    config_lines: >-
      Defaults timestamp_timeout={{ ask_password_timeout }}

